[package]
name = "tes-parse"
version = "0.1.0"
authors = ["Adam Gleave"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4"
nom = "5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"