[package]
name = "tes-parse"
version = "0.1.0"
authors = ["Adam Gleave"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
byteorder = "1.4.2"
lazy_static = "1.4.0"
log = "0.4.14"
nom = "6.1.2"

[dev-dependencies]
ctor = "0.1.19"
env_logger = "0.8.3"